[project]
name = "antialias"
version = "0.1.0"
description = "Invoke your bash functions from one place."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click~=8.1",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.8.0",
]

[project.scripts]
antialias = "antialias:cli"
