name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        check:
          - ruff check
          - ruff format --check
          - pytest -v

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: uv-venv
      uses: andgineer/uv-venv@v1.1
    - name: Install dependencies
      run: |
        uv sync --frozen
    - name: Check
      run: |
        ${{ matrix.check }}
