# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: uv-venv
      uses: andgineer/uv-venv@v1.1
    - name: Install dependencies
      run: |
        uv sync --frozen
    - name: Lint with ruff
      run: |
        ruff check
    - name: Test with pytest
      run: |
        pytest
